export enum Role {
    USER = 'USER',
    ADMIN = 'ADMIN',
    BUYER = 'BUYER',
    PRODUGIE_OPS = 'PRODUGIE_OPS',
    LSA_CERTIFIED = 'LSA_CERTIFIED',
    LSA_NOMINATED = 'LSA_NOMINATED',
    TEAM_MANAGER = 'TEAM_MANAGER',
    TEAM_MEMBER = 'TEAM_MEMBER',
}